---
- hosts: all
  tasks:
    - block:
        - name: Install Apache
          apt: name=apache2 state=presented

        - name: Start Apache
          service: name=apache2 state=started
      become: true
      when: ansible_os_family == "Debian"
      rescue:
        - debug:
            msg: "From rescue block"
      always:
        - debug:
            msg: "From always block"

    - block:
        - name: Install httpd
          yum: name=httpd state=present
          ignore_errors: yes

        - name: Start httpd
          service: name=httpd state=started

        - name: Print logs
          command: cat /var/log/server.log
          register: command_output
          failed_when: "'ERROR' in command_output.stdout"
      become: true
      when: ansible_os_family == "RedHat"

