---
- hosts: all
  tasks:
    - block:
        - name: Install Apache
          apt: name=apache2 state=presented

        - name: Start Apache
          service: name=apache2 state=started
      become: true
      when: ansible_os_family == "Debian"
      rescue:
        - debug:
            msg: "From rescue block"
      always:
        - debug:
            msg: "From always block"

    - block:
        - name: Install httpd
          yum: name=httpd state=present

        - name: Start httpd
          service: name=httpd state=started
      become: true
      when: ansible_os_family == "RedHat"

