---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch Instance
      ec2:
        key_name: "ohio"
        aws_access_key: "Place_your_AWS_access_key"
        aws_secret_key: "Place_your_AWS_secret_key"
        group: "launch-wizard-1"
        instance_type: "t2.micro"
        image: "ami-002068ed284fb165b"
        wait: true
        region: "us-east-2"
        count: 1
        count_tag:
          Name: "Automatic"
        instance_tags:
          Name: "Automatic"
        vpc_subnet_id: "subnet-99f5f1f0"
        assign_public_ip: yes
      register: ec2

    - name: Add instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groups:
        - web_servers
      with_items: "{{ ec2.instances }}"

    - debug:
        msg: Remote IP is "{{ item.private_ip }}"
      with_items: "{{ ec2.instances }} "

    - name: Add in inventory file
      lineinfile: 
        path: /home/ec2-user/ansible-demo/hosts
        insertafter: '^web1'
        line: "web2 ansible_host={{ item.private_ip }}"
      with_items: "{{ ec2.instances }}"

    - pause:
        prompt: waiting for 1 mins
        minutes: 1
    - name: Install python
      shell: 
        ssh -i key.pem ec2-user@{{ item.private_ip }}
        sudo yum update -y && sudo yum install python -y && sudo yum install git -y
      with_items: "{{ ec2.instances }}"

    - name: Install GIT
      shell:
        ssh -i key.pem ec2-user@{{ item.private_ip }}
        sudo yum install git -y
      with_items: "{{ ec2.instances }}"

    - name: export SSH key
      shell: cat ~/.ssh/id_rsa.pub | ssh -i key.pem ec2-user@{{ item.private_ip }} "cat >> ~/.ssh/authorized_keys"
      become_user: ec2-user
      delegate_to: localhost
      with_items: "{{ ec2.instances }}"

    - name: Refresh Inventory
      meta: refresh_inventory

- name: Configure Instance
  hosts: web2
  become: true
  gather_facts: true
  tasks:
    - name: Install apache
      yum: name=httpd state=present

    - name: Start apache
      service: name=httpd state=started enabled=yes

    - name: Deploy application
      git:
        repo: https://github.com/pathakbhaskar/test.git
        dest: /var/www/html
        update: yes
        force: yes




