---
- hosts: all
  vars:
    test4: 4.4.4.4
  tasks:
    - name: Print local variable
      debug:
        msg: "{{ hostvars['web1'].test1 }}"
          

    - name: Print play variable
      debug:
        msg: "{{ test4 }}"

    - name: Pring group variable
      debug:
        msg: "{{ test3 }}"
